### ISSUE TITLE
Expected a JavaScript module script but the server responded with a MIME type of "text/plain"

### ISSUE THREAD

**Issue by Jaykingamez** [Linnest2020/Vic3-mapdata-editor#5]
![image](https://user-images.githubusercontent.com/39272482/198822142-37b1bbce-0ac7-4812-84eb-3d47a598e23f.png)

Tried both V1.0.2 and V1.0.22, allowed network access

**Comment by Linnest2020** [comment]
In my community, there is the same problems rarely, too. However, until I changed `start.go` and get this problem ONCE by coincidence, it never raise such problem. 

Some solution in network are told you to change registor, however, I dont know if it work, and I can't get feedback. Therefore I attempt to fixed it on `start.go` by setting `Content-Type`, and publish [v1.0.3](https://github.com/Linnest2020/Vic3-mapdata-editor/releases/tag/v1.0.3). May it can works.

**Comment by Linnest2020** [comment]
Further, never allowed network access in the editor, it is totally local.

**Comment by Jaykingamez** [comment]
谢谢，我会试试一下

**Comment by Linnest2020** [comment]
It maybe done, if there is anymore problem it will reopen
